### ISSUE TITLE
stacked-bar3d

### ISSUE THREAD

**Issue by personlin** [JohnCoene/echarts#10]
Hi John,
Is it possible to add stacked-bar3d ?
http://echarts.baidu.com/examples/editor.html?c=stacked-bar3d&gl=1
Thank you~

**Comment by JohnCoene** [comment]
The package is for ECharts 2.7 http://echarts.baidu.com/echarts2/index-en.html

I'm working on another package to have ECharts 4 which was just released.

**Comment by personlin** [comment]
Good to hear that !!

**Comment by JohnCoene** [comment]
You can check JohnCoene/echarts4r, no doc it's still a work in progress, a lot will change and break look at e_bar_3d function and use the stack argument like in this package.
