### ISSUE TITLE
auto resize of charts

### ISSUE THREAD

**Issue by maymenw** [JohnCoene/echarts#9]
When I create a chart in Rstudio window or Shiny app there is no option for the charts to automatically resize to fit my window. 

For example if I launch my app on browser when I make my browser full screen or smaller the chart doesnt seem to resize automatically

I even tried the following in ui
tags$head(tags$style( type = 'text/css',  '#plot{ overflow-x: scroll; }')),
  echartsOutput('plot')

**Comment by JohnCoene** [comment]
Thanks for flagging that: added resize method from echarts2, it's now fully responsive:, tested in RStudio viewer and Shiny 👍 .

Reinstall and use just as you did before, it should be fully responsive.

```r
devtools::install_github("JohnCoene/echarts")

mtcars %>%
  echart(mpg) %>%
  eline(drat)
```

Resize the viewer. Feel free to re-open if it does not work.

**Comment by maymenw** [comment]
Thanks yup works perfectly
